name: Deploy DKMedia API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14" # Specify explicit version

      - name: Install Dependencies
        run: npm ci # Clean install for consistency

      - name: Build Application
        run: npm run build # Ensure lowercase if package.json uses "build"

      - name: Sync Files to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: "/var/www/dkmedia-api" # Update to actual path
          ARGS:  "-az --delete --rsync-path='sudo rsync' --exclude='node_modules/' --exclude='.git/' --exclude='.env'"

      - name: Restart API Service
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/dkmedia-api
            npm ci --production  # Install prod dependencies
            pm2 restart dkmedia-api  # Use PM2 for process management